### ISSUE TITLE
Error after upgrading from 1.31.0 to 1.32.6

### ISSUE THREAD

**Issue by natschoman** [vazco/meteor-universe-i18n#158]
I am on the latest meteor version 2.7.3 with every packages up to date except universe:i18n.
If I try to update it to the latest version 1.32.6 my App breaks with blank screen and following error in the browser console log 

modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:234 Uncaught Error: Cannot find module 'events'
    at makeMissingError (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:234:12)
    at Module.resolve (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:249:17)
    at Module.moduleLink [as link] (modules.js?hash=624e1d1c9b72425c7313fc6de410ecbed7b6e989:321:25)
    at module (common.ts:1:39)
    at fileEvaluate (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:388:7)
    at Module.require (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:270:27)
    at Module.moduleLink [as link] (modules.js?hash=624e1d1c9b72425c7313fc6de410ecbed7b6e989:328:22)
    at module (client.ts:1:40)
    at fileEvaluate (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:388:7)
    at Module.require (modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:270:27)
makeMissingError @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:234
Module.resolve @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:249
moduleLink @ modules.js?hash=624e1d1c9b72425c7313fc6de410ecbed7b6e989:321
module @ common.ts:1
fileEvaluate @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:388
require @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:270
moduleLink @ modules.js?hash=624e1d1c9b72425c7313fc6de410ecbed7b6e989:328
module @ client.ts:1
fileEvaluate @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:388
require @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:270
require @ modules-runtime-hot.js?hash=1baba75a2760fb8ea6e194ad2f188f86fb440126:310
(anonymous) @ universe_i18n.js?hash=7839379c77a22a7928913950b56163b0e4a6f0d4:1616
(anonymous) @ universe_i18n.js?hash=7839379c77a22a7928913950b56163b0e4a6f0d4:1624
global-imports.js?hash=04b54e521d5b280926f502c6eaa8a2b7b39d6b26:7 Uncaught TypeError: Cannot read properties of undefined (reading 'i18n')
    at global-imports.js?hash=04b54e521d5b280926f502c6eaa8a2b7b39d6b26:7:33
(anonymous) @ global-imports.js?hash=04b54e521d5b280926f502c6eaa8a2b7b39d6b26:7
app.js?hash=46412071a52f584fee68afc89805aea57fdf3ce1:1 Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=46412071a52f584fee68afc89805aea57fdf3ce1:1:15

Any ideas would be appreciated :)

**Comment by piotrpospiech** [comment]
Hi, I tried to reproduce this issue, but it works for me. I think maybe you have a broken package build. You should have this line 
`var meteorInstall = Package.modules.meteorInstall;` in the `.meteor/local/build/programs/server/packages/universe_i18n.js`. 

Try to run `meteor remove universe:i18n` and install it again

**Comment by natschoman** [comment]
Hi @piotrpospiech, after removing and installing the package again it is working now. Thx!
